-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 4c90c9557da7c0d695d6a729bae8b1de4e496cbf
    hooks:
    -   id: check-added-large-files
        args:
        - --maxkb=20
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: trailing-whitespace
-   repo: git://github.com/bjbishop/commit_tally
    sha: 6facad67919a86c938e06cd1559497c9266afbee
    hooks:
    -   id: commit_tally
-   repo: git://github.com/bjbishop/commit_habitrpg
    sha: f15ec72ea787db47985a62d2051a61f6d63bb862
    hooks:
    -   id: commit_habitrpg
